# Generated by Django 5.1.3 on 2024-11-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Plm',
        ),
    ]
